name: Deploy Appery.io App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies (Opcional)
      run: npm install  # Solo si usas Node.js o tienes un package.json

    - name: Build Project (Opcional)
      run: npm run build  # Solo si necesitas compilar tu proyecto

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Carpeta donde está tu index.html
